Introduce proper `MaskedEq` poly
lurk-lab/arecibo pull request #162
Opened 2023-12-05 12:02 UTC by adr1anh

This PR introduces a new `MaskesEqPolynomial` which is equal to an `EqPolynomial` over the same $n$ random values, except over the first $2^m$ evaluations where it equals zero. 

We use it in the `WitnessBoundSumcheck` to ensure the `W` polynomial only contains values in the first `num_vars` entries.

2023-12-05 19:29 UTC, huitseeker commented on src/spartan/polys/masked_eq.rs
> +}
Should this be?
```rust
pub struct MaskedEqPolynomial<'a, Scalar: PrimeField> {
  eq: &'a EqPolynomial<Scalar>,
  num_masked_vars: usize,
}
```

2023-12-05 19:35 UTC, huitseeker reviewed
1. Do we want to manipulate an owned `EqPolynomial` or a reference to such an `EqPolynomial`? What I'm getting at is that if the `MaskedPolynomial` only exists as a thin wrapper on the way to getting its `.evals()`, https://github.com/lurk-lab/arecibo/pull/157 has shown (on the `EqPolynomial`) that this pattern leads to uneeded copies.
2. If the answer is "yeah, there's an upcoming instance where I will need to act on this `MaskedPolynomial` mutably", have you considered a cow ? (as in [Cow](https://doc.rust-lang.org/std/borrow/enum.Cow.html) not 🐄 )

2023-12-05 19:35 UTC, huitseeker commented on src/spartan/polys/masked_eq.rs
> +pub struct MaskedEqPolynomial<Scalar: PrimeField> {
This needs to derive `Debug` at least.

2023-12-06 03:47 UTC, mpenciak approved these changes

2023-12-06 15:26 UTC, huitseeker requested changes
I had a quick look and I can confirm that `MaskedEqPolynomial` operating by reference does avoid needless cloning. I've opened https://github.com/adr1anh/arecibo/pull/2

2023-12-06 17:11 UTC, huitseeker approved these changes
🙏

2023-12-06 17:57 UTC, merged