ci: Add Solidity compatibility check
lurk-lab/arecibo pull request #363
Opened 2024-03-13 02:12 UTC by samuelburnham

Checks Solidity compatibility on every PR commit, comments on failure, and opens an issue in https://github.com/lurk-lab/solidity-verifier if a failing commit is merged. This surfaces issues early and lets authors/reviewers decide how to address breaking changes.

2024-03-13 15:09 UTC, huitseeker submitted a review, later dismissed
This looks great!

2024-03-13 16:28 UTC, storojs72 requested changes
Discussed issues with @samuelburnham in DM.

The CI compatibility job needs to be modified - so that it runs compatibility tests in Rust (only for IPA currently), dynamically generates unit tests for Solidity, copies those tests into fetched solidity-verifier directory and finally runs them. Rust <-> Solidity Incompatibility over particular building block can be detected by failure of dynamically generated (by Rust) and executed (in Solidity) unit-test

2024-03-14 17:05 UTC, storojs72 approved these changes
LGTM

2024-03-14 17:41 UTC, samuelburnham commented on .github/workflows/solidity.yml
> +          cargo nextest run -E 'test(test_solidity_compatibility)' --release --run-ignored all --nocapture > test-output
Yes, documented

2024-03-14 18:18 UTC, storojs72 approved these changes
Excellent! Thanks

2024-03-14 18:44 UTC, huitseeker approved these changes

2024-03-14 20:10 UTC, merged